# TODO replace `%productname%` with the product name in lower case

name: %productname%-local

services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: %productname%
      POSTGRES_PASSWORD: %productname%
      POSTGRES_DB: %productname%
      # With this configuration, password is no longer required to login PostgreSQL
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - %productname%-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=%productname%", "--dbname=%productname%", "--host=localhost", "--port=5432" ]
      interval: 1s
      timeout: 1m

  localstack:
    image: localstack/localstack:s3-latest
    restart: always
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - %productname%-localstack:/var/lib/localstack
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 1s
      timeout: 1m

volumes:
  %productname%-db: {}
  %productname%-localstack: {}
