experimental_monorepo_root = true

[monorepo]
config_roots = [ "projects/*" ]

[tools]
node = "24"
"npm:nushell" = "latest"

[tasks]
  [tasks.dev]
  run = [
    "podman compose ls > /dev/null",
    "//projects/...:dev",
  ]

  [tasks.build]
  run =[{ task = "//projects/...:build" }]

  [tasks.test]
  run =[{ task = "//projects/...:test" }]

  [tasks.lint]
  depends = [ "//projects/...:lint" ]
  run = [
    "tsc --noEmit",
    "eslint",
  ]

  [tasks.fix]
  run = "eslint --fix"

  [tasks.clean]
  run = [
    "git clean -dX --exclude=\"!.env\" --exclude=\"!mise.local.toml\" --force",
    { task = "clean:containers" }
  ]

  [tasks.refresh]
  depends = [ "clean" ]
  run = [
    "rm --force ./pnpm-lock.yaml",
    "corepack enable",
    "corepack up",
    "pnpm install"
  ]

  # TODO Add this task if the project includes npm package(s)
  [tasks.publish]
  run =[{ task = "//projects/...:publish" }]

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile", # TODO remove --frozen-lockfile if pnpm-lock.yaml is not included in this repo
]

[env]
_.file = ".env"
_.path = "./node_modules/.bin"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
