[tasks]
  [tasks.dev]
  run = "vite"

  [tasks.build]
  run = "vite build"
  env = { NODE_ENV = "production" }

  [tasks.test]
  run = "vitest run"

  [tasks.lint]
  run = "tsc --noEmit"

[env]
_.path = "./node_modules/.bin"
