name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Remove Podman which does not work well on GitHub Actions
        run: sudo apt remove -y podman

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - run: mise lint
      - run: mise build

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist
          path: dist # TODO Change build directory
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  test:
    name: test on Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version:
          - 20
          - 22
          - 24
    env:
      # Override Node.js version over mise.toml
      MISE_NODE_VERSION: ${{ matrix.node-version }}
    steps:
      - name: Remove Podman which does not work well on GitHub Actions
        run: sudo apt remove -y podman

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - run: mise test

  release:
    needs:
      - build-lint
      - test
    # TODO Only required for Cloudflare Workers
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # ▼▼ TODO Only required for Cloudflare Workers ▼▼
    permissions:
      contents: read
      pull-requests: write
    # ▲▲ TODO Only required for Cloudflare Workers ▲▲
    steps:
      - name: Remove Podman which does not work well on GitHub Actions
        run: sudo apt remove -y podman

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          install: true
          cache: true

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: dist
          path: dist # TODO Change build directory

      # ▼▼ TODO Add this section if the project is deployed to Cloudflare Workers ▼▼
      - name: deploy Worker
        id: deployment
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          environment: ${{ github.event_name == 'release' && 'production' || 'staging'  }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Add comment for deployment URL
        run: "gh pr comment ${{ github.event.number }} --edit-last --create-if-none --body 'Deployed to staging:\n${{ steps.deployment.outputs.pages-deployment-alias-url && steps.deployment.outputs.pages-deployment-alias-url || steps.deployment.outputs.deployment-url }}'"
      # ▲▲ TODO Add this section if the project is deployed to Cloudflare Workers ▲▲

      # ▼▼ TODO Add this section if the deploy command can be executed with `mise deploy` ▼▼
      - run: mise build
      - run: mise deploy
      # ▲▲ TODO Add this section if the deploy command can be executed with `mise deploy` ▲▲

      # ▼▼ TODO Add this section if the project is an npm package ▼▼
      - run: mise build

      - name: Set npm auth token
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
      - run: mise publish
      # ▲▲ TODO Add this section if the project is an npm package ▲▲
