[tools]
node = "24"
"npm:nushell" = "latest"

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile", # TODO remove --frozen-lockfile if pnpm-lock.yaml is not included in this repo
]

[env]
_.file = ".env"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
